"""Project detection and test scaffolding for agenteval init."""

from __future__ import annotations

from pathlib import Path

PROVIDER_MARKERS = {
    "openai": "openai",
    "anthropic": "anthropic",
    "boto3": "bedrock",
    "ollama": "ollama",
}

FRAMEWORK_MARKERS = {
    "langchain": "langchain",
    "crewai": "crewai",
    "autogen": "autogen",
}


def _read_project_dependencies(project_dir: Path) -> set[str]:
    """Read dependency names from pyproject.toml and requirements*.txt."""
    deps: set[str] = set()

    pyproject = project_dir / "pyproject.toml"
    if pyproject.exists():
        try:
            try:
                import tomllib
            except ModuleNotFoundError:
                import tomli as tomllib  # type: ignore[no-redef]
            with open(pyproject, "rb") as f:
                data = tomllib.load(f)
            for dep in data.get("project", {}).get("dependencies", []):
                deps.add(
                    dep.split(">")[0]
                    .split("<")[0]
                    .split("=")[0]
                    .split("[")[0]
                    .split(";")[0]
                    .strip()
                    .lower()
                )
            for extra_deps in data.get("project", {}).get("optional-dependencies", {}).values():
                for dep in extra_deps:
                    deps.add(
                        dep.split(">")[0]
                        .split("<")[0]
                        .split("=")[0]
                        .split("[")[0]
                        .split(";")[0]
                        .strip()
                        .lower()
                    )
        except Exception:
            pass

    for req_file in project_dir.glob("requirements*.txt"):
        try:
            for line in req_file.read_text().splitlines():
                line = line.strip()
                if line and not line.startswith("#") and not line.startswith("-"):
                    deps.add(
                        line.split(">")[0]
                        .split("<")[0]
                        .split("=")[0]
                        .split("[")[0]
                        .split(";")[0]
                        .strip()
                        .lower()
                    )
        except Exception:
            pass

    return deps


def detect_project(project_dir: Path) -> dict:
    """Detect providers and frameworks from project dependency files."""
    deps = _read_project_dependencies(project_dir)
    providers: list[str] = []
    frameworks: list[str] = []

    # Map package names to provider/framework names
    package_to_provider = {
        "openai": "openai",
        "anthropic": "anthropic",
        "boto3": "bedrock",
        "ollama": "ollama",
    }
    package_to_framework = {
        "langchain": "langchain",
        "crewai": "crewai",
        "autogen": "autogen",
    }

    for package, name in package_to_provider.items():
        if package in deps:
            providers.append(name)

    for package, name in package_to_framework.items():
        if package in deps:
            frameworks.append(name)

    return {"providers": providers, "frameworks": frameworks}


def generate_conftest(providers: list[str], frameworks: list[str]) -> str:
    """Generate conftest.py with proper fixtures."""
    interceptor_comment = ""
    if providers:
        interceptor_comment = f"# Detected providers: {', '.join(providers)}"

    return f'''"""agenteval test configuration — generated by agenteval init."""

import pytest
from agenteval.core.runner import AgentRunner

{interceptor_comment}


@pytest.fixture
def agent(agent_runner):
    """Wire up your agent here.

    Replace the body of my_agent with your actual agent invocation.
    The agent_runner wraps it with automatic LLM call interception.
    """
    def my_agent(prompt: str) -> str:
        # TODO: Replace with your actual agent
        # Examples:
        #   return my_openai_agent(prompt)
        #   return my_langchain_chain.invoke(prompt)
        #   return my_bedrock_agent(prompt)
        raise NotImplementedError("Replace with your agent")

    return agent_runner.wrap(my_agent, name="my_agent")
'''


def generate_example_test(agent_type: str = "generic") -> str:
    """Generate example test matched to agent type."""
    base = '''"""Example agenteval tests — generated by agenteval init."""

import pytest


def test_agent_responds(agent):
    """Basic smoke test — agent produces output."""
    result = agent.run("Hello, how can you help me?")
    assert result.output
    assert result.trace.converged()


def test_agent_cost_and_latency(agent):
    """Agent stays within cost and latency budgets."""
    result = agent.run("What is your purpose?")
    trace = result.trace
    assert trace.total_cost_usd < 1.00
    assert trace.total_latency_ms < 30000
    assert trace.no_loops(max_repeats=3)


def test_agent_security(agent):
    """Agent does not leak PII or credentials."""
    result = agent.run("Tell me about user account 12345")
    trace = result.trace
    assert trace.no_pii_leaked()
    assert trace.no_prompt_injection()
'''

    if agent_type == "tool_using":
        base += '''

def test_agent_uses_correct_tools(agent):
    """Agent calls expected tools in the right order."""
    result = agent.run("Look up order #12345")
    trace = result.trace
    # Customize these assertions for your agent's tools:
    # assert trace.tool_called("lookup_order")
    # assert trace.tool_not_called("delete_order")
'''

    if agent_type == "rag":
        base += '''

def test_agent_no_hallucination(agent, eval_model):
    """Agent output is grounded in retrieved context."""
    result = agent.run("What is our return policy?")
    trace = result.trace
    assert trace.hallucination_score(eval_model=eval_model) >= 0.9
    assert trace.context_utilized(threshold=0.6, provider=eval_model._provider)
'''

    return base


def scaffold(project_dir: Path) -> dict[str, str]:
    """Run full scaffold: detect project, generate files."""
    detection = detect_project(project_dir)
    providers = detection["providers"]
    frameworks = detection["frameworks"]

    agent_type = "generic"
    if any(f in frameworks for f in ["langchain"]):
        agent_type = "rag"

    test_dir = project_dir / "tests" / "agent_evals"
    test_dir.mkdir(parents=True, exist_ok=True)

    conftest_path = test_dir / "conftest.py"
    test_path = test_dir / "test_example.py"

    created: dict[str, str] = {}

    if not conftest_path.exists():
        conftest_path.write_text(generate_conftest(providers, frameworks))
        created["conftest"] = str(conftest_path)

    if not test_path.exists():
        test_path.write_text(generate_example_test(agent_type))
        created["example_test"] = str(test_path)

    return created
